services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: canopy-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_URI=postgresql://postgres:1234@postgres:5432/canopy_db
      - MONGO_URI=mongodb://mongo:27017/canopy_users
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: canopy-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: canopy-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: canopy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:7
    container_name: canopy-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
